---
# Clip length in seconds
clip_len : 10

# Working sample rate
sample_rate : 44100

# Spleeter model
spl_mod : '4stems'

# Input representation
input_mode : "vqt"                        # can be vqt or cqt

# Data directory for pre-text and downstream tasks
pt_data_dir : "fma_large/"

# Stem check values
lower_p : .3
upper_p : 1.

# Pretext task to run
pt_task: "clmr"                           # can be 'zerons' or 'clmr'

# Training and model parameters
lr         : 0.000001
temp       : .25
num_epochs : 250
batch_size : 16        
val_len    : 6400    
train_pkl  : 2880

# SMC Mirex
smc_exp    : "beat"                       # can be 'beat' or 'perc'
smc_status : "pretrained"                 # can be 'pretrained', 'old-school', 'clmr', or 'vanilla'
smc_pre    : "finetune"                   # can be 'frozen', 'validation', or 'finetune'
smc_eval   : "dbn"                        # can be 'threshold', 'librosa', or 'dbn'
smc_lr     : 0.00001                      # learning rate

# Ballroom
ballroom_exp    : "beat"                  # can be 'beat' or 'perc'
ballroom_status : "pretrained"            # can be 'pretrained', 'old-school', 'clmr', or 'vanilla'
ballroom_pre    : "finetune"              # can be 'frozen', 'validation', or 'finetune'
ballroom_eval   : "dbn"                   # can be 'threshold', 'librosa', or 'dbn'
ballroom_lr     : 0.00001                 # learning rate

# Hainsworth
hainsworth_exp    : "beat"                # can be 'beat' or 'perc'
hainsworth_status : "pretrained"          # can be 'pretrained', 'old-school', 'clmr', or 'vanilla'
hainsworth_pre    : "finetune"            # can be 'frozen', 'validation', or 'finetune'
hainsworth_eval   : "dbn"                 # can be 'threshold', 'librosa', or 'dbn'
hainsworth_lr     : 0.00001               # learning rate

# GTZAN
gtzan_exp    : "beat"                     # can be 'beat' or 'perc'
gtzan_status : "pretrained"               # can be 'pretrained', 'old-school', 'clmr', or 'vanilla'
gtzan_pre    : "finetune"                 # can be 'frozen', 'validation', or 'finetune'
gtzan_eval   : "dbn"                      # can be 'threshold', 'librosa', or 'dbn'
gtzan_lr     : 0.00001                    # learning rate

# Cross data experiment
cross_status    : "pretrained"            # can be 'pretrained', 'clmr', or 'vanilla'
cross_pre       : "finetune"              # can be 'frozen' or 'finetune'
cross_train_set : "smc"                   # can be 'hainsworth', 'ballroom', or 'smc'
cross_eval      : "dbn"                   # can be 'threshold' or 'dbn'
cross_lr        : 0.00001                 # learning rate

# Measurement experiment
measave   : True                          # True: GTZAN saved at 44100 Hz
meastatus : "std"                         # can be 'drums', 'ros', 'van', 'rand', 'mix', 'clmr', 'std', or 'bock'